---
- hosts: all
  remote_user: vagrant
  tasks:
  - name: check if gvm is installed
    shell: test -d /home/vagrant/.gvm && echo "yes" || echo "no"
    register: is_gvm_installed

  - name: install unzip
    apt: name=unzip state=latest update_cache=yes
    sudo: yes

  - name: install java
    apt: name=openjdk-7-jdk state=latest update_cache=yes
    sudo: yes
 
  - name: download gvm
    when: is_gvm_installed.stdout == "no"
    get_url: url=http://get.gvmtool.net dest="/home/vagrant/gvm_install.sh" mode=0774

  - name: install gvm
    when: is_gvm_installed.stdout == "no"
    shell: /home/vagrant/gvm_install.sh >> log.txt 

  - name: install grails
    shell: bash -lc "yes | gvm install grails" executable=/bin/bash


